import type { Deal } from "./types";

export type SharedPackagePayload = {
  version: 1;
  generatedAt: string;
  source: "estate";
  disclaimer: string;
  deal: Deal;
};

export function buildSharedPackagePayload(deal: Deal): SharedPackagePayload {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    source: "estate",
    disclaimer:
      "Generated by Estate · not an MLS listing, appraisal, or lending commitment.",
    deal: {
      ...deal,
      // Snapshot: strip nothing — lender package is self-contained
    },
  };
}

export function isSharedPackagePayload(
  value: unknown,
): value is SharedPackagePayload {
  if (!value || typeof value !== "object") return false;
  const v = value as SharedPackagePayload;
  return (
    v.version === 1 &&
    v.deal != null &&
    typeof v.deal === "object" &&
    typeof v.deal.id === "string"
  );
}

export function newShareToken(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID().replace(/-/g, "");
  }
  return `pkg_${Math.random().toString(36).slice(2)}${Date.now().toString(36)}`;
}
