"use client";

import type { Deal } from "@/lib/types";
import { PackageDocument } from "./PackageDocument";

export function SharedPackageView({
  deal,
  generatedAt,
}: {
  deal: Deal;
  generatedAt: string;
}) {
  return (
    <div className="bank-package min-h-screen bg-[#faf9f7] text-[#111]">
      <div className="print:hidden sticky top-14 z-30 border-b border-[#ddd] bg-[#faf9f7]/95 backdrop-blur">
        <div className="mx-auto flex max-w-[8.5in] flex-wrap items-center justify-between gap-3 px-5 py-3">
          <p className="text-sm text-[#555]">
            Read-only cost package · Generated by Estate · not MLS appraisal
          </p>
          <button
            type="button"
            onClick={() => window.print()}
            className="bg-[#12352c] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#1f5c48]"
          >
            Download PDF for bank
          </button>
        </div>
      </div>
      <PackageDocument deal={deal} shared generatedAt={generatedAt} />
    </div>
  );
}
