import type { Metadata } from "next";
import { loadSharedPackage } from "@/lib/package-store";
import { SharedPackageView } from "@/components/SharedPackageView";
import { BRAND_NAME } from "@/lib/brand";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: `${BRAND_NAME} — Shared bank package`,
  description: `Read-only construction / acquisition cost package. Generated by ${BRAND_NAME} — not an MLS appraisal.`,
  robots: { index: false, follow: false },
};

export default async function SharedPackagePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const payload = await loadSharedPackage(token);

  if (!payload) {
    return (
      <div className="mx-auto max-w-lg px-6 py-24 text-center">
        <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-muted">
          Package
        </p>
        <p className="mt-3 font-display text-3xl tracking-tight">
          Link not found
        </p>
        <p className="mt-3 text-sm text-muted">
          This share link may have expired or is invalid.
        </p>
      </div>
    );
  }

  return (
    <SharedPackageView
      deal={payload.deal}
      generatedAt={payload.generatedAt}
    />
  );
}
